export type LayoutPreset = 'sidebar' | 'top' | 'ide';

/** First-run / missing-pref default: IDE layout with editor tabs (see `ide-dark` in THEMES). */
export const DEFAULT_THEME_ID = 'ide-dark';

export interface ThemeDefinition {
  id: string;
  name: string;
  layout: LayoutPreset;
  variables: Record<string, string>;
}

const baseVars = {
  '--mnemo-radius': '6px',
  '--mnemo-sidebar-width': '16rem',
};

export const THEMES: ThemeDefinition[] = [
  {
    id: 'dark-default',
    name: 'Dark (default)',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#0f0f0f',
      '--mnemo-bg-panel': '#111111',
      '--mnemo-bg-panel-elevated': '#1a1a1a',
      '--mnemo-bg-hover': '#1a1a1a',
      '--mnemo-bg-active': '#1a1a2e',
      '--mnemo-border': '#1e1e1e',
      '--mnemo-border-strong': '#333333',
      '--mnemo-text': '#e4e4e7',
      '--mnemo-text-muted': '#888888',
      '--mnemo-text-dim': '#555555',
      '--mnemo-accent': '#7c7cff',
      '--mnemo-on-accent': '#0a0a0a',
      '--mnemo-category-bar': '#141418',
    },
  },
  {
    id: 'dark-contrast',
    name: 'Dark contrast',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#09090b',
      '--mnemo-bg-panel': '#0c0c0f',
      '--mnemo-bg-panel-elevated': '#18181b',
      '--mnemo-bg-hover': '#27272a',
      '--mnemo-bg-active': '#3f3f46',
      '--mnemo-border': '#3f3f46',
      '--mnemo-border-strong': '#52525b',
      '--mnemo-text': '#fafafa',
      '--mnemo-text-muted': '#a1a1aa',
      '--mnemo-text-dim': '#71717a',
      '--mnemo-accent': '#a78bfa',
      '--mnemo-on-accent': '#0a0a0a',
      '--mnemo-category-bar': '#12121a',
    },
  },
  {
    id: 'light',
    name: 'Light',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#f4f4f5',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#f4f4f5',
      '--mnemo-bg-hover': '#ececf2',
      '--mnemo-bg-active': '#e0e7ff',
      '--mnemo-border': '#d4d4d8',
      '--mnemo-border-strong': '#a1a1aa',
      '--mnemo-text': '#0a0a0b',
      '--mnemo-text-muted': '#52525c',
      '--mnemo-text-dim': '#71717a',
      '--mnemo-accent': '#4338ca',
      '--mnemo-category-bar': '#e8e8ed',
    },
  },
  {
    id: 'light-contrast',
    name: 'Light (high contrast)',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#e4e4e7',
      '--mnemo-bg-panel': '#fafafa',
      '--mnemo-bg-panel-elevated': '#f4f4f5',
      '--mnemo-bg-hover': '#e4e4e7',
      '--mnemo-bg-active': '#c7d2fe',
      '--mnemo-border': '#a1a1aa',
      '--mnemo-border-strong': '#71717a',
      '--mnemo-text': '#000000',
      '--mnemo-text-muted': '#3f3f46',
      '--mnemo-text-dim': '#52525b',
      '--mnemo-accent': '#3730a3',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#d4d4d8',
    },
  },
  {
    id: 'light-warm',
    name: 'Light warm',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#faf8f5',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#f5f0e8',
      '--mnemo-bg-hover': '#f0ebe3',
      '--mnemo-bg-active': '#ffedd5',
      '--mnemo-border': '#e7e2d9',
      '--mnemo-border-strong': '#c4b8a8',
      '--mnemo-text': '#1c1917',
      '--mnemo-text-muted': '#57534e',
      '--mnemo-text-dim': '#78716c',
      '--mnemo-accent': '#c2410c',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#f0ebe3',
    },
  },
  {
    id: 'light-paper',
    name: 'Light paper',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#f1f5f9',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#f8fafc',
      '--mnemo-bg-hover': '#e2e8f0',
      '--mnemo-bg-active': '#dbeafe',
      '--mnemo-border': '#cbd5e1',
      '--mnemo-border-strong': '#94a3b8',
      '--mnemo-text': '#0f172a',
      '--mnemo-text-muted': '#475569',
      '--mnemo-text-dim': '#64748b',
      '--mnemo-accent': '#0369a1',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#e8f0f8',
    },
  },
  {
    id: 'light-blue',
    name: 'Light sky',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#f0f9ff',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#e0f2fe',
      '--mnemo-bg-hover': '#dbeafe',
      '--mnemo-bg-active': '#bfdbfe',
      '--mnemo-border': '#bae6fd',
      '--mnemo-border-strong': '#7dd3fc',
      '--mnemo-text': '#0c1222',
      '--mnemo-text-muted': '#475569',
      '--mnemo-text-dim': '#64748b',
      '--mnemo-accent': '#1d4ed8',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#e0f2fe',
    },
  },
  {
    id: 'light-top',
    name: 'Light (top layout)',
    layout: 'top',
    variables: {
      ...baseVars,
      '--mnemo-sidebar-width': '0px',
      '--mnemo-bg-app': '#f4f4f5',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#f4f4f5',
      '--mnemo-bg-hover': '#ececf2',
      '--mnemo-bg-active': '#e0e7ff',
      '--mnemo-border': '#d4d4d8',
      '--mnemo-border-strong': '#a1a1aa',
      '--mnemo-text': '#0a0a0b',
      '--mnemo-text-muted': '#52525c',
      '--mnemo-text-dim': '#71717a',
      '--mnemo-accent': '#4338ca',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#e8e8ed',
    },
  },
  {
    id: 'sepia',
    name: 'Sepia',
    layout: 'sidebar',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#1c1917',
      '--mnemo-bg-panel': '#292524',
      '--mnemo-bg-panel-elevated': '#44403c',
      '--mnemo-bg-hover': '#57534e',
      '--mnemo-bg-active': '#78716c',
      '--mnemo-border': '#44403c',
      '--mnemo-border-strong': '#57534e',
      '--mnemo-text': '#fafaf9',
      '--mnemo-text-muted': '#a8a29e',
      '--mnemo-text-dim': '#78716c',
      '--mnemo-accent': '#d97706',
      '--mnemo-on-accent': '#0a0a0a',
      '--mnemo-category-bar': '#231f1c',
    },
  },
  {
    id: 'dark-top',
    name: 'Dark (top layout)',
    layout: 'top',
    variables: {
      ...baseVars,
      '--mnemo-sidebar-width': '0px',
      '--mnemo-bg-app': '#0f0f0f',
      '--mnemo-bg-panel': '#111111',
      '--mnemo-bg-panel-elevated': '#1a1a1a',
      '--mnemo-bg-hover': '#1a1a1a',
      '--mnemo-bg-active': '#1a1a2e',
      '--mnemo-border': '#1e1e1e',
      '--mnemo-border-strong': '#333333',
      '--mnemo-text': '#e4e4e7',
      '--mnemo-text-muted': '#888888',
      '--mnemo-text-dim': '#555555',
      '--mnemo-accent': '#7c7cff',
      '--mnemo-on-accent': '#0a0a0a',
      '--mnemo-category-bar': '#0a0a12',
    },
  },
  {
    id: 'ide-dark',
    name: 'Dark (IDE)',
    layout: 'ide',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#0f0f0f',
      '--mnemo-bg-panel': '#111111',
      '--mnemo-bg-panel-elevated': '#1a1a1a',
      '--mnemo-bg-hover': '#1a1a1a',
      '--mnemo-bg-active': '#1a1a2e',
      '--mnemo-border': '#1e1e1e',
      '--mnemo-border-strong': '#333333',
      '--mnemo-text': '#e4e4e7',
      '--mnemo-text-muted': '#888888',
      '--mnemo-text-dim': '#555555',
      '--mnemo-accent': '#7c7cff',
      '--mnemo-on-accent': '#0a0a0a',
      '--mnemo-category-bar': '#141418',
    },
  },
  {
    id: 'ide-light',
    name: 'Light (IDE)',
    layout: 'ide',
    variables: {
      ...baseVars,
      '--mnemo-bg-app': '#f4f4f5',
      '--mnemo-bg-panel': '#ffffff',
      '--mnemo-bg-panel-elevated': '#f4f4f5',
      '--mnemo-bg-hover': '#ececf2',
      '--mnemo-bg-active': '#e0e7ff',
      '--mnemo-border': '#d4d4d8',
      '--mnemo-border-strong': '#a1a1aa',
      '--mnemo-text': '#0a0a0b',
      '--mnemo-text-muted': '#52525c',
      '--mnemo-text-dim': '#71717a',
      '--mnemo-accent': '#4338ca',
      '--mnemo-on-accent': '#ffffff',
      '--mnemo-category-bar': '#e8e8ed',
    },
  },
];

export function getTheme(id: string): ThemeDefinition {
  return THEMES.find(t => t.id === id) ?? THEMES.find(t => t.id === DEFAULT_THEME_ID) ?? THEMES[0]!;
}

export function applyThemeToDocument(theme: ThemeDefinition): void {
  const root = document.documentElement;
  root.setAttribute('data-theme', theme.id);
  root.setAttribute('data-layout', theme.layout);
  for (const [k, v] of Object.entries(theme.variables)) {
    root.style.setProperty(k, v);
  }
}
